[build-system]
requires      = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dbtools"
version = "0.0.1"
description = "Database tools for schema mapping, integrity check and migration"
readme = "README.md"
authors = [
    { name = "Fran Vargas", email = "fvarrui.ceu@gmail.com" }
]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = ["db", "tools", "schema", "mapping", "integrity", "check", "migration", "sql" ]
dependencies = [
    "tabulate",    
    "python-dotenv",
    "sqlalchemy",
    "pymysql",          # MySQL/MariaDB
    "pyodbc",           # SQL Server
    "psycopg2",         # PostgreSQL
]
requires-python = ">=3.12"

[project.optional-dependencies]
dev = ["black", "bumpver", "isort", "pip-tools", "pytest"]

[project.urls]

[project.scripts]
dbchecker = "dbchecker.__main__:main"
dbschema = "dbschema.__main__:main"

[tool.setuptools]
include-package-data = true